### ISSUE TITLE
Failed to install the app

### ISSUE THREAD

**Issue by himanshi4708** [credebl/adeya-wallet#118]
I cloned this repo and tried to run it but its giving me the following error after "yarn run android":

error Failed to install the app. Command failed with exit code 1: gradlew.bat tasks
Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131) at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349) at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292) at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287) at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356) at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231) at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174) at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421) at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182) at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) at 

Any idea what is the solution for this? How can this error be resolved?

**Comment by sairanjit** [comment]
@himanshi4708 Can you please verify that your `JAVA_HOME` path is set correctly?  Looks like the issue is specific to android setup

**Comment by himanshi4708** [comment]
hi @sairanjit, i have set the path for JAVA_HOME as C:\Program Files\RedHat\java-11-openjdk-11.0.10-1
Still facing this issue.

Apart from this, i have another doubt regarding import/export wallet feature. The export feature is working for me and i have a backup created in my phone directory.
While performing the import feature, credential.id and credential.key are coming undefined in logs.
This error is related to file "importwalletconfirmation.tsx". After clicking the verify button it just keeps on loading and does not import wallet.

**Comment by sairanjit** [comment]
@himanshi4708 Are you still facing the above issue ?

**Comment by amitpadmani-awts** [comment]
@himanshi4708 Closing this issue due to lack of response. Please reopen if further assistance is needed.
